### PR TITLE
[NOREF] Seed data for echimp

### PR DESCRIPTION
**Pull request by StevenWadeOddball**
## Description
1. Introduce seed data with existing echimp model data
2. Update Postman collection

## How to test this change

1.  Query  the seeded model plan, look at the related echimp CR or TDL
2. ( you can use the updated postman collection to do the query)

## PR Author Checklist

- [ ] I have provided a detailed description of the changes in this PR.
- [ ] I have provided clear instructions on how to test the changes in this PR.
- [ ] I have updated tests or written new tests as appropriate in this PR.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

### CODE REVIEW

**Review by patrickseguraoddball — CHANGES_REQUESTED** [review]
Thanks Steven.  I'm still getting this error when trying to create a model plan manually.  I'm open to sync if you are

```
"failed to get S3 object: NoSuchKey: The specified key does not exist. status code: 404, request id: 17F8D2CA6B44E612, host id: d0af7ef13e9a79de08686e85c361d9af88c5ebdbbacf07a734ab2c11fd85e57f"
```

**Comment by patrickseguraoddball** [comment]
I realize this may have been outside scope, but this was the original issue I brought to clay.  I'm unable to query the model plan when querying `echimpCRsAndTDLs`.  This is the error it throws.

**Comment by StevenWadeOddball** [comment]
Thanks @patrickseguraoddball! As we discussed, the error occurs locally when data is not seeded.  Though not a result of this PR, we decided to implement a change to address this in this PR!

Now, if you can't get the cache, we should expect that nil is returned, and an error is logged in the backend. This will make sure we are alerted if this happens in a deployed environment, but allows flexibility when developing. You can confirm that the error shouldn't exist in the GQL response now, but you can look at the docker logs to see an error is logged if you query echimp crs or tdls without seeded data.

**Review by patrickseguraoddball — APPROVED** [review]
LG Thanks!

**Pull request merged**
